### ISSUE TITLE
Error 400 when deleting client

### ISSUE THREAD

**Issue by mashaole** [bradtraversy/project-mgmt-graphql#12]
when i run the delete client mutation it gave me an error and i found  the solution through the browser

i change ID! to STRING!

**Comment by chirag-chhajed** [comment]
I have turned ID! to STRING! but still getting the error

**Comment by mashaole** [comment]
Maybe check out this repo I put it on and retrace the error and how I fixed it https://github.com/IAmPresenting/MernaQ-template

**Comment by chirag-chhajed** [comment]
> Maybe check out this repo I put it on and retrace the error and how I fixed it https://github.com/IAmPresenting/MernaQ-template

Hey thanks, it's working now. It was a silly syntax error previously.

**Comment by mashaole** [comment]
Nice 👌🏾👌🏾we can now close the issue
